/**
 * Simulates a call to an AI service to get a response for a given prompt.
 * @param {string} prompt - The user's prompt.
 * @returns {Promise<string>} A promise that resolves with a simulated AI response.
 */
export const getAIResponse = (prompt) => {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(`This is a simulated AI response. In a real application, this would be a detailed answer generated by an AI model based on the prompt: '${prompt}'.`);
    }, 1500);
  });
};
